---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sitejsvh/nodewebstormexpress/
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH